### ISSUE TITLE
How do I load my own point cloud file?

### ISSUE THREAD

**Issue by victoryc** [walzimmer/3d-bat#3]
I would like to load my own point cloud file (.pcd) and annotate it by placing some bounding boxes. Can I do that with this tool? 
I didn't see any instructions regarding how to load our own point cloud files.

**Comment by abhigoku10** [comment]
@victoryc  can you please let me knw how did u load your own point cloud and annotate it ?? should i pass only pcd files or even bin s r fine

**Comment by victoryc** [comment]
@abhigoku10. We ended up writing our own proprietory tool.

**Comment by davodogster** [comment]
@victoryc Hi Victor do you know any very good point cloud annotation tools??
